/**
 * LiveKit Token Service for DearGluco.ai
 *
 * This service handles secure token generation for LiveKit sessions.
 * Since this is a Vite frontend app, tokens must be generated by a backend server
 * to keep LiveKit API secrets secure.
 */

import { AccessToken } from 'livekit-server-sdk';
import { RoomAgentDispatch, RoomConfiguration } from '@livekit/protocol';
import { DIABETES_CONSULTATION_CONFIG, ROOM_CONFIG } from '../lib/livekit-config';

export interface TokenRequest {
  participantName: string;
  roomName?: string;
  glucoseLevel?: number;
  sessionType?: 'consultation' | 'emergency' | 'followup';
  metadata?: Record<string, any>;
}

export interface ParticipantSummary {
  identity: string;
  name: string;
  metadata: string;
  permission: {
    canSubscribe: boolean;
    canPublish: boolean;
    canPublishData: boolean;
    canUpdateMetadata: boolean;
  };
}

export interface TokenResponse {
  accessToken: string;
  url: string;
  participantInfo: ParticipantSummary;
  roomName: string;
}

/**
 * Generate a unique room name for the consultation
 */
export function generateRoomName(sessionType: string = 'consultation'): string {
  const timestamp = Date.now();
  const random = Math.floor(Math.random() * 10000);
  return `diabetes_${sessionType}_${timestamp}_${random}`;
}

/**
 * Generate a unique participant identity
 */
export function generateParticipantIdentity(participantName: string): string {
  const timestamp = Date.now();
  const random = Math.floor(Math.random() * 1000);
  return `patient_${participantName.replace(/\s+/g, '_')}_${timestamp}_${random}`;
}

/**
 * Create participant permissions for diabetes consultation
 */
export function createConsultationPermissions() {
  return {
    canSubscribe: true,
    canPublish: true,
    canPublishData: true,
    canUpdateMetadata: true,
  };
}

/**
 * Request a LiveKit token from the backend server
 * This is the secure way to get tokens in a production environment
 */
export async function requestTokenFromBackend(tokenRequest: TokenRequest): Promise<TokenResponse> {
  try {
    const response = await fetch('/api/livekit-token', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(tokenRequest),
    });

    if (!response.ok) {
      throw new Error(`Token request failed: ${response.statusText}`);
    }

    return await response.json();
  } catch (error) {
    console.error('Backend token request failed:', error);
    throw new Error('Tidak dapat mendapatkan token konsultasi. Periksa koneksi internet Anda.');
  }
}

/**
 * Development/Demo token generation (CLIENT-SIDE ONLY)
 * WARNING: This should NEVER be used in production as it exposes API secrets
 * Only for local development when backend is not available
 */
export async function generateTokenDevelopment(tokenRequest: TokenRequest): Promise<TokenResponse> {
  if (import.meta.env.PROD) {
    throw new Error('Development token generation not allowed in production');
  }

  const apiKey = import.meta.env.VITE_LIVEKIT_API_KEY;
  const apiSecret = import.meta.env.VITE_LIVEKIT_API_SECRET;
  const wsUrl = import.meta.env.VITE_LIVEKIT_URL;

  if (!apiKey || !apiSecret || !wsUrl) {
    throw new Error('LiveKit development credentials not configured');
  }

  try {
    const roomName = tokenRequest.roomName || generateRoomName(tokenRequest.sessionType);
    const participantIdentity = generateParticipantIdentity(tokenRequest.participantName);
    const permissions = createConsultationPermissions();

    // Do NOT pre-create the room — token-based agent dispatch is silently
    // ignored for rooms that already exist (LiveKit server behaviour).
    // The room will be auto-created when the participant joins with this token.

    const token = new AccessToken(apiKey, apiSecret, {
      identity: participantIdentity,
      name: tokenRequest.participantName,
      ttl: 60 * 60,
      metadata: JSON.stringify({
        sessionType: tokenRequest.sessionType || 'consultation',
        glucoseLevel: tokenRequest.glucoseLevel,
        timestamp: Date.now(),
        ...tokenRequest.metadata,
      }),
    });

    token.addGrant({
      roomJoin: true,
      room: roomName,
      canPublish: permissions.canPublish,
      canSubscribe: permissions.canSubscribe,
      canPublishData: permissions.canPublishData,
      canUpdateOwnMetadata: permissions.canUpdateMetadata,
    });

    token.roomConfig = new RoomConfiguration({
      emptyTimeout: 30,
      departureTimeout: 10,
      agents: [
        new RoomAgentDispatch({
          agentName: DIABETES_CONSULTATION_CONFIG.agentName,
        }),
      ],
    });

    const jwt = await token.toJwt();

    console.log('Token created for room:', roomName, '— agent dispatch:', DIABETES_CONSULTATION_CONFIG.agentName);

    return {
      accessToken: jwt,
      url: wsUrl,
      participantInfo: {
        identity: participantIdentity,
        name: tokenRequest.participantName,
        metadata: token.metadata || '',
        permission: permissions,
      },
      roomName,
    };
  } catch (error) {
    console.error('Development token generation failed:', error);
    throw new Error('Gagal membuat token konsultasi');
  }
}

/**
 * Main token service - automatically chooses between backend and development mode
 */
export async function getConsultationToken(tokenRequest: TokenRequest): Promise<TokenResponse> {
  // In development, use development mode directly (no backend needed)
  if (import.meta.env.DEV) {
    console.log('Using development token generation (no backend required)');
    return generateTokenDevelopment(tokenRequest);
  }

  // In production, only use backend
  return await requestTokenFromBackend(tokenRequest);
}

/**
 * Create a complete token request with medical context
 */
export function createConsultationTokenRequest(
  participantName: string,
  options: {
    glucoseLevel?: number;
    sessionType?: 'consultation' | 'emergency' | 'followup';
    symptoms?: string[];
    medicationList?: string[];
    lastMealTime?: Date;
  } = {}
): TokenRequest {
  return {
    participantName,
    roomName: generateRoomName(options.sessionType),
    glucoseLevel: options.glucoseLevel,
    sessionType: options.sessionType || 'consultation',
    metadata: {
      symptoms: options.symptoms || [],
      medicationList: options.medicationList || [],
      lastMealTime: options.lastMealTime?.toISOString(),
      language: 'id', // Indonesian
      timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
    },
  };
}

/**
 * Validate token request for medical safety
 */
export function validateTokenRequest(request: TokenRequest): { valid: boolean; errors: string[] } {
  const errors: string[] = [];

  if (!request.participantName?.trim()) {
    errors.push('Nama pasien diperlukan');
  }

  if (request.glucoseLevel && (request.glucoseLevel < 20 || request.glucoseLevel > 600)) {
    errors.push('Kadar gula darah harus antara 20-600 mg/dL');
  }

  if (request.sessionType && !['consultation', 'emergency', 'followup'].includes(request.sessionType)) {
    errors.push('Tipe sesi tidak valid');
  }

  return {
    valid: errors.length === 0,
    errors,
  };
}